### PR TITLE
Add Python 3.11 to workflow

### PR DESCRIPTION
**Pull request by mvdwetering**

### CODE REVIEW

**Comment by mvdwetering** [comment]
Note to self: Can only be done after bumping minumum HA version to 2023.2

**Comment by mvdwetering** [comment]
HA does not support 3.11 right now. This needs to wait until that is merged

**Comment by ChristophCaina** [comment]
Ha now requires Python 3.11 with 2023.6

**Comment by mvdwetering** [comment]
Implemented by #173

**Pull request closed without merging**
